In [1]:
day = 8

In [2]:
# import pandas as pd
import numpy as np

import os

In [3]:
INPUT_DIR = "../input"

input_path = f'{INPUT_DIR}/day{day:02d}.txt'

data = []
with open(input_path) as file:
#     data = file.readlines()
    for line in file.readlines():
        data.append(line.strip('\n'))

In [4]:
data[:15]

['100021112110202312022010330204312040000111012143445142221414240220240442332040010320133120230011020',
 '111110201332323210211143123214321343332124211413115514155115511033421001222101204330001300333011010',
 '222100123300231230122203432310224441551434231352112532354252244334410042212441233243220102033110020',
 '212210311310102334321243104133012535144151532555155341325352512544453402400411340202133231000102020',
 '112002102322001003304233302040124544411225523533534235113353522233535550432232202401221022110311110',
 '112102131331201432320312233124434232544144233241123334112232531521542551332434224211234133132330300',
 '201212231001314001232020011521543445152251413225334151155332443144315433444321403022301110231133320',
 '222200212012234021440323522251222114255435321245463652634454445441313331334221403314121340322201323',
 '011101313030124034011053132411352313135432265223564644563435541314314453511355132441242220212301210',
 '33012032000441422400122534232513354112562266556326344443423263

In [5]:
len(data)

99

## parse data

In [16]:
x = data[0]
x

'100021112110202312022010330204312040000111012143445142221414240220240442332040010320133120230011020'

In [21]:
[int(y) for y in x][:10]

[1, 0, 0, 0, 2, 1, 1, 1, 2, 1]

In [22]:
data_parsed = [int(y) for x in data for y in x]

In [23]:
data_parsed[:10]

[1, 0, 0, 0, 2, 1, 1, 1, 2, 1]

In [24]:
len(data_parsed)

9801

In [25]:
data_arr = np.array(data_parsed)

In [26]:
data_arr = np.reshape(data_arr, (99,99))

In [27]:
data_arr[0]

array([1, 0, 0, 0, 2, 1, 1, 1, 2, 1, 1, 0, 2, 0, 2, 3, 1, 2, 0, 2, 2, 0,
       1, 0, 3, 3, 0, 2, 0, 4, 3, 1, 2, 0, 4, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       2, 1, 4, 3, 4, 4, 5, 1, 4, 2, 2, 2, 1, 4, 1, 4, 2, 4, 0, 2, 2, 0,
       2, 4, 0, 4, 4, 2, 3, 3, 2, 0, 4, 0, 0, 1, 0, 3, 2, 0, 1, 3, 3, 1,
       2, 0, 2, 3, 0, 0, 1, 1, 0, 2, 0])

In [28]:
data_arr.shape

(99, 99)

In [30]:
data_arr[0, 2]

0

# dev logic

Day notes:
- A tree is visible if all of the other trees between it and an edge of the grid are shorter than it
    - same height => not visible
- Trees in exterior of grid are visible

How many trees are visible?

Example:
```
    30373
    25512
    65332
    33549
    35390
```

In [39]:
ex_data = """30373
25512
65332
33549
35390"""
ex_data_list = ex_data.split("\n")
ex_data_parsed = [int(y) for x in ex_data_list for y in x]
ex_data_arr = np.array(ex_data_parsed)
ex_data_arr = np.reshape(ex_data_arr, (5,5))

In [40]:
ex_data_arr

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])

In [46]:
i, j = 1,1
val = ex_data_arr[i][j]
up_neighbors = [ex_data_arr[x][j] for x in range(i)]

In [47]:
val, up_neighbors

(5, [0])

In [48]:
val < max(up_neighbors)

False

Tree is visible

In [49]:
i, j = 1,3
val = ex_data_arr[i][j]
up_neighbors = [ex_data_arr[x][j] for x in range(i)]
print(val < max(up_neighbors))
val, up_neighbors

True


(1, [7])

In [74]:
5 < max([3,3,2])

False

In [76]:
5 <= max([5,3,2])

True

Tree is not visisble

In [51]:
i, j = 1,3
val = ex_data_arr[i][j]
print(val)
is_visible = False

while not is_visible:

    up_neighbors = [ex_data_arr[x][j] for x in range(i)]
    if val < max(up_neighbors):
        is_visible = False
    else:
        is_visible = True
    
    down_neighbors = [ex_data_arr[x][j] for x in range(i+1, ex_data_arr.shape[0])]
    if val < max(down_neighbors):
        is_visible = False
    else:
        is_visible = True
    
    left_neighbors = [ex_data_arr[i][x] for x in range(j)]
    if val < max(left_neighbors):
        is_visible = False
    else:
        is_visible = True   
    
    right_neighbors = [ex_data_arr[i][x] for x in range(j+1, ex_data_arr.shape[1])]
    if val < max(right_neighbors):
        is_visible = False
    else:
        is_visible = True
    
    break
    
print(is_visible)

1
False


In [52]:
i, j = 2,1
val = ex_data_arr[i][j]
print(val)
is_visible = False

while not is_visible:

    up_neighbors = [ex_data_arr[x][j] for x in range(i)]
    if val < max(up_neighbors):
        is_visible = False
    else:
        is_visible = True
    
    down_neighbors = [ex_data_arr[x][j] for x in range(i+1, ex_data_arr.shape[0])]
    if val < max(down_neighbors):
        is_visible = False
    else:
        is_visible = True
    
    left_neighbors = [ex_data_arr[i][x] for x in range(j)]
    if val < max(left_neighbors):
        is_visible = False
    else:
        is_visible = True   
    
    right_neighbors = [ex_data_arr[i][x] for x in range(j+1, ex_data_arr.shape[1])]
    if val < max(right_neighbors):
        is_visible = False
    else:
        is_visible = True
    
    break
    
print(is_visible)

5
True


In [55]:
def check_if_vis(i, j, data_arr):
    val = data_arr[i][j]

    is_visible = False

    while not is_visible:

        up_neighbors = [data_arr[x][j] for x in range(i)]
        if val < max(up_neighbors):
            is_visible = False
        else:
            is_visible = True

        down_neighbors = [data_arr[x][j] for x in range(i+1, data_arr.shape[0])]
        if val < max(down_neighbors):
            is_visible = False
        else:
            is_visible = True

        left_neighbors = [data_arr[i][x] for x in range(j)]
        if val < max(left_neighbors):
            is_visible = False
        else:
            is_visible = True   

        right_neighbors = [data_arr[i][x] for x in range(j+1, data_arr.shape[1])]
        if val < max(right_neighbors):
            is_visible = False
        else:
            is_visible = True

        break

    return is_visible

In [62]:
ex_data_arr.shape

(5, 5)

In [65]:
def count_num_vis(data_arr):
    num_vis = 0
    for i in range(data_arr.shape[0]):
        for j in range(data_arr.shape[1]):
            if (i == 0) or (j == 0) or (i == (data_arr.shape[0]-1)) or (j == (data_arr.shape[1]-1)):
                num_vis += 1
            else:
                if check_if_vis(i, j, data_arr):
                    num_vis += 1
    return num_vis

In [66]:
count_num_vis(ex_data_arr)

21

In [67]:
count_num_vis(data_arr)

2121

## troubleshoot

In [69]:


def count_num_vis(data_arr):
    num_vis = 0
    vis_list = []
    for i in range(data_arr.shape[0]):
        for j in range(data_arr.shape[1]):
            if (i == 0) or (j == 0) or (i == (data_arr.shape[0]-1)) or (j == (data_arr.shape[1]-1)):
                num_vis += 1
                vis_list.append([i,j])
            else:
                if check_if_vis(i, j, data_arr):
                    num_vis += 1
                    vis_list.append([i,j])
    print(num_vis)
    return vis_list

In [70]:
data_arr.shape

(99, 99)

In [71]:
vis_list = count_num_vis(data_arr)

2121


In [73]:
vis_list[100:120]

[[1, 50],
 [1, 51],
 [1, 55],
 [1, 56],
 [1, 59],
 [1, 60],
 [1, 66],
 [1, 80],
 [1, 81],
 [1, 82],
 [1, 87],
 [1, 90],
 [1, 91],
 [1, 92],
 [1, 94],
 [1, 95],
 [1, 97],
 [1, 98],
 [2, 0],
 [2, 36]]

In [86]:
if 5 <= max([0]):
    is_visible = False
else:
    is_visible = True

print(is_visible)

True


In [87]:
if 5 <= max([5,1,2]):
    is_visible = False
else:
    is_visible = True

print(is_visible)

False


In [90]:
def check_if_vis(i, j, data_arr):
    val = data_arr[i][j]

    is_visible = False

    while not is_visible:

        up_neighbors = [data_arr[x][j] for x in range(i)]
        if val <= max(up_neighbors): # if smaller than or equal to its neighbors, tree is *not* visible
            is_visible = False
        else:
            print("Tree is visible from the top")
            is_visible = True

        down_neighbors = [data_arr[x][j] for x in range(i+1, data_arr.shape[0])]
        if val <= max(down_neighbors):
            is_visible = False
        else:
            print("Tree is visible from the bottom")
            is_visible = True

        left_neighbors = [data_arr[i][x] for x in range(j)]
        if val <= max(left_neighbors):
            is_visible = False
        else:
            print("Tree is visible from the left")
            is_visible = True

        right_neighbors = [data_arr[i][x] for x in range(j+1, data_arr.shape[1])]
        if val <= max(right_neighbors):
            is_visible = False
        else:
            print("Tree is visible from the right")
            is_visible = True

        break

    return is_visible

In [91]:
check_if_vis(1,1, ex_data_arr)

Tree is visible from the top
Tree is visible from the left


False

In [92]:
5 > min([0])

True

In [93]:
if 5 > min([5,1,2]):
    is_visible = False
else:
    is_visible = True

print(is_visible)

False


In [110]:
def check_if_vis(i, j, data_arr):
    val = data_arr[i][j]
    print(val)
    is_visible = False

    up_neighbors = [data_arr[x][j] for x in range(i)]
    if val > max(up_neighbors):
        print("Tree is visible from the top", up_neighbors)
#         return True
        is_visible = True

    down_neighbors = [data_arr[x][j] for x in range(i+1, data_arr.shape[0])]
    if val > max(down_neighbors):
        print("Tree is visible from the bottom", down_neighbors)
#         return True
        is_visible = True
    
    left_neighbors = [data_arr[i][x] for x in range(j)]
    if val > max(left_neighbors):
        print("Tree is visible from the left", left_neighbors)
#         return True
        is_visible = True

    right_neighbors = [data_arr[i][x] for x in range(j+1, data_arr.shape[1])]
    if val > max(right_neighbors):
        print("Tree is visible from the right", right_neighbors)
#         return True
        is_visible = True

    return is_visible

In [111]:
check_if_vis(1,1, ex_data_arr)

5
Tree is visible from the top [0]
Tree is visible from the left [2]


True

In [108]:
5 > max([2])

True

In [109]:
5 > max([5, 1, 2])

False

In [103]:
ex_data_arr

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])

In [100]:
ex_data_arr[1][1]

5

In [115]:
def check_if_vis(i, j, data_arr):
    val = data_arr[i][j]
#     print(val)
    is_visible = False

    up_neighbors = [data_arr[x][j] for x in range(i)]
    if val > max(up_neighbors):
#         print("Tree is visible from the top", up_neighbors)
        is_visible = True

    down_neighbors = [data_arr[x][j] for x in range(i+1, data_arr.shape[0])]
    if val > max(down_neighbors):
#         print("Tree is visible from the bottom", down_neighbors)
        is_visible = True
    
    left_neighbors = [data_arr[i][x] for x in range(j)]
    if val > max(left_neighbors):
#         print("Tree is visible from the left", left_neighbors)
        is_visible = True

    right_neighbors = [data_arr[i][x] for x in range(j+1, data_arr.shape[1])]
    if val > max(right_neighbors):
#         print("Tree is visible from the right", right_neighbors)
        is_visible = True

    return is_visible

In [116]:
def count_num_vis(data_arr):
    num_vis = 0
    vis_list = []
    for i in range(data_arr.shape[0]):
        for j in range(data_arr.shape[1]):
            if (i == 0) or (j == 0) or (i == (data_arr.shape[0]-1)) or (j == (data_arr.shape[1]-1)):
                num_vis += 1
                vis_list.append([i,j])
            else:
                if check_if_vis(i, j, data_arr):
                    num_vis += 1
                    vis_list.append([i,j])
    print(num_vis)
    return vis_list

In [118]:
ex_vis_list = count_num_vis(ex_data_arr)

21


In [119]:
vis_list = count_num_vis(data_arr)

1796


# part 2

Notes:
- If a tree is right on the edge, at least one of its viewing distances will be zero

In [122]:
def count_num_trees(val, neighbors):
    num_trees = 0
    for n in neighbors:
        if n < val:
            num_trees += 1
        elif n >= val:
            num_trees += 1
            break
    return num_trees

In [123]:
val = 5
neighbors = [3,5,3]
# [x < val for x in neighbors]
count_num_trees(val, neighbors)

2

In [124]:
val = 5
neighbors = [4,9]
count_num_trees(val, neighbors)

2

In [125]:
val = 5
neighbors = [5,2,3]
count_num_trees(val, neighbors)

1

In [135]:
def get_scenic_score(i, j, data_arr):
    val = data_arr[i][j]
    print(f"val: {val}")
#     score = 1

    up_neighbors = [data_arr[x][j] for x in range(i-1, -1, -1)]
    up_score = count_num_trees(val, up_neighbors)
    print(up_score)
#     score *= count_num_trees(val, up_neighbors)

    down_neighbors = [data_arr[x][j] for x in range(i+1, data_arr.shape[0])]
#     score *= count_num_trees(val, down_neighbors)
    down_score = count_num_trees(val, down_neighbors)
    print(down_score)
    
    left_neighbors = [data_arr[i][x] for x in range(j-1, -1, -1)]
#     score *= count_num_trees(val, left_neighbors)
    left_score = count_num_trees(val, left_neighbors)
    print(left_score)

    right_neighbors = [data_arr[i][x] for x in range(j+1, data_arr.shape[1])]
#     score *= count_num_trees(val, right_neighbors)
    right_score = count_num_trees(val, right_neighbors)
    print(right_score)
    
    score = up_score * down_score * left_score * right_score

    return score

In [127]:
ex_data_arr

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])

In [136]:
get_scenic_score(1,2,ex_data_arr)

val: 5
1
2
1
2


4

In [137]:
get_scenic_score(3, 2, ex_data_arr)

val: 5
2
1
2
2


8

In [141]:
def get_scenic_score(i, j, data_arr):
    val = data_arr[i][j]
#     print(f"val: {val}")
#     score = 1

    up_neighbors = [data_arr[x][j] for x in range(i-1, -1, -1)]
    up_score = count_num_trees(val, up_neighbors)
#     print(up_score)
#     score *= count_num_trees(val, up_neighbors)

    down_neighbors = [data_arr[x][j] for x in range(i+1, data_arr.shape[0])]
#     score *= count_num_trees(val, down_neighbors)
    down_score = count_num_trees(val, down_neighbors)
#     print(down_score)
    
    left_neighbors = [data_arr[i][x] for x in range(j-1, -1, -1)]
#     score *= count_num_trees(val, left_neighbors)
    left_score = count_num_trees(val, left_neighbors)
#     print(left_score)

    right_neighbors = [data_arr[i][x] for x in range(j+1, data_arr.shape[1])]
#     score *= count_num_trees(val, right_neighbors)
    right_score = count_num_trees(val, right_neighbors)
#     print(right_score)
    
    score = up_score * down_score * left_score * right_score

    return score

In [142]:
def find_best_spot(data_arr):
    best_score = 0
    for i in range(data_arr.shape[0]):
        for j in range(data_arr.shape[1]):
            if (i == 0) or (j == 0) or (i == (data_arr.shape[0]-1)) or (j == (data_arr.shape[1]-1)):
                # score = 0, so can't be the best
                continue
            else:
                spot_score = get_scenic_score(i, j, data_arr)
                if spot_score > best_score:
                    best_score = spot_score
                    best_spot = [i, j]
    print(best_score)
    return best_spot

In [143]:
find_best_spot(ex_data_arr)

8


[3, 2]

In [144]:
find_best_spot(data_arr)

288120


[86, 49]